apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: yashparmar2055/doctorappoitment-backend
        ports:
        - containerPort: 4000
        envFrom:
        - secretRef:
            name: backend-secret