apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: yashparmar2055/doctorappoitment-admin
        ports:
        - containerPort: 5174
        env:
        - name: VITE_BACKEND_URL
          value: "http://backend-service:4000"