apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  MONGODB_URI: 'Your Data'
  CLOUDINARY_NAME: 'Your Data'
  CLOUDINARY_API_KEY: 'Your Data'
  CLOUDINARY_SECRET_KEY: 'Your Data'
  ADMIN_EMAIL: 'admin@prescripto.com'
  ADMIN_PASSWORD: 'admin123'
  JWT_SECRET: 'Your Data'
  RAZORPAY_KEY_ID: 'Your Data'
  RAZORPAY_KEY_SECRET: 'Your Data'
