apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: yashparmar2055/doctorappoitment-frontend
        ports:
        - containerPort: 5173
        env:
        - name: VITE_BACKEND_URL
          value: "http://backend-service:4000"
        - name: VITE_RAZORPAY_KEY_ID
          valueFrom:
            secretKeyRef:
              name: frontend-secret
              key: VITE_RAZORPAY_KEY_ID